#!/usr/bin/env python3
"""
balance_watcher.py
Watch our Base wallet address for incoming USDC transfer events
generated by x402 agent queries.

Usage:
  python balance_watcher.py              # Run once, check current balance + recent events
  python balance_watcher.py --daemon     # Run continuous watcher (blocks until Ctrl+C)
  python balance_watcher.py --daemon --interval 30  # Check every 30 seconds

Requirements:
  pip install web3 python-dotenv
  Set BASE_RPC_URL env var (or use default public RPC)
  Set USDC_CONTRACT_ADDRESS if different from standard Base USDC
"""

import os
import sys
import time
import json
from datetime import datetime
from typing import Optional

try:
    from web3 import Web3
    from web3.exceptions import BlockNotFound
except ImportError:
    print("[X] web3.py not installed. Run: pip install web3")
    sys.exit(1)

# Configuration
WALLET_ADDRESS = "0x8Ae639d10b23Eb630241d7fD6275255a2e51Ec95"
USDC_CONTRACT_ADDRESS = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"  # Base Mainnet USDC
USDC_DECIMALS = 6

# Base RPC endpoints (public, no auth required)
DEFAULT_RPC_URLS = [
    "https://mainnet.base.org",                    # Official Base RPC
    "https://base.llamarpc.com",                   # Llama RPC
    "https://base-rpc.publicnode.com",             # PublicNode
    "https://1rpc.io/base",                        # 1RPC
]

# USDC ABI (minimal for balanceOf + Transfer event)
USDC_ABI = json.loads('''[
    {"inputs":[{"internalType":"address","name":"account","type":"address"}],"name":"balanceOf","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
    {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"from","type":"address"},{"indexed":true,"internalType":"address","name":"to","type":"address"},{"indexed":false,"internalType":"uint256","name":"value","type":"uint256"}],"name":"Transfer","type":"event"}
]''')

class BalanceWatcher:
    def __init__(self, rpc_url: Optional[str] = None, interval: int = 30):
        self.rpc_url = rpc_url or os.getenv("BASE_RPC_URL") or DEFAULT_RPC_URLS[0]
        self.interval = interval
        self.w3 = None
        self.contract = None
        self.last_block = None
        
    def connect(self) -> bool:
        """Initialize Web3 connection."""
        print(f"[*] Connecting to Base RPC: {self.rpc_url}")
        try:
            self.w3 = Web3(Web3.HTTPProvider(self.rpc_url, request_kwargs={"timeout": 10}))
            if not self.w3.is_connected():
                print("[X] Failed to connect to RPC")
                return False
            
            # Verify chain ID is Base (8453)
            chain_id = self.w3.eth.chain_id
            if chain_id != 8453:
                print(f"[!] Warning: Connected to chain {chain_id}, expected 8453 (Base)")
            
            self.contract = self.w3.eth.contract(
                address=Web3.to_checksum_address(USDC_CONTRACT_ADDRESS),
                abi=USDC_ABI
            )
            
            self.last_block = self.w3.eth.block_number
            print(f"[+] Connected. Chain ID: {chain_id}, Current block: {self.last_block}")
            return True
            
        except Exception as e:
            print(f"[X] Connection error: {e}")
            return False
    
    def get_balance(self) -> float:
        """Get current USDC balance."""
        try:
            balance_wei = self.contract.functions.balanceOf(
                Web3.to_checksum_address(WALLET_ADDRESS)
            ).call()
            return balance_wei / (10 ** USDC_DECIMALS)
        except Exception as e:
            print(f"[X] Balance check error: {e}")
            return 0.0
    
    def get_recent_transfers(self, from_block: int, to_block: int) -> list:
        """Query Transfer events for our wallet."""
        try:
            # Create filter for transfers TO our address
            transfer_filter = self.contract.events.Transfer.create_filter(
                fromBlock=from_block,
                toBlock=to_block,
                argument_filters={"to": Web3.to_checksum_address(WALLET_ADDRESS)}
            )
            events = transfer_filter.get_all_entries()
            return events
        except Exception as e:
            print(f"[X] Event query error: {e}")
            return []
    
    def format_transfer(self, event) -> dict:
        """Format a Transfer event for display."""
        return {
            "tx_hash": event.transactionHash.hex(),
            "block": event.blockNumber,
            "from": event.args["from"],
            "to": event.args["to"],
            "value_usdc": event.args["value"] / (10 ** USDC_DECIMALS),
            "timestamp": datetime.utcnow().isoformat() + "Z"  # Approximate
        }
    
    def check_once(self) -> dict:
        """Single balance + events check."""
        if not self.w3 or not self.w3.is_connected():
            if not self.connect():
                return {"error": "Not connected"}
        
        current_block = self.w3.eth.block_number
        balance = self.get_balance()
        
        result = {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "wallet": WALLET_ADDRESS,
            "balance_usdc": balance,
            "current_block": current_block,
            "new_transfers": []
        }
        
        # Check for new transfers since last check
        if self.last_block is not None and current_block > self.last_block:
            events = self.get_recent_transfers(self.last_block + 1, current_block)
            for event in events:
                transfer = self.format_transfer(event)
                result["new_transfers"].append(transfer)
                print(f"\n[+] NEW TRANSFER DETECTED!")
                print(f"    Tx: {transfer['tx_hash']}")
                print(f"    From: {transfer['from']}")
                print(f"    Value: {transfer['value_usdc']} USDC")
                print(f"    Block: {transfer['block']}")
        
        self.last_block = current_block
        return result
    
    def run_daemon(self):
        """Continuous monitoring loop."""
        print(f"[*] Starting balance watcher daemon (interval: {self.interval}s)")
        print(f"[*] Wallet: {WALLET_ADDRESS}")
        print(f"[*] Press Ctrl+C to stop\n")
        
        if not self.connect():
            return 1
        
        # Initial balance
        balance = self.get_balance()
        print(f"[+] Initial balance: {balance:.6f} USDC\n")
        
        try:
            while True:
                try:
                    self.check_once()
                    time.sleep(self.interval)
                except KeyboardInterrupt:
                    print("\n[*] Watcher stopped by user.")
                    break
                except Exception as e:
                    print(f"[X] Loop error: {e}")
                    print(f"[*] Reconnecting in 10s...")
                    time.sleep(10)
                    self.connect()
        except KeyboardInterrupt:
            pass
        
        final_balance = self.get_balance()
        print(f"\n[+] Final balance: {final_balance:.6f} USDC")
        return 0


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Base USDC Balance Watcher for x402 revenue")
    parser.add_argument("--daemon", action="store_true", help="Run continuous watcher")
    parser.add_argument("--interval", type=int, default=30, help="Check interval in seconds (daemon mode)")
    parser.add_argument("--rpc", type=str, help="Custom Base RPC URL")
    parser.add_argument("--once", action="store_true", help="Single check and exit")
    
    args = parser.parse_args()
    
    watcher = BalanceWatcher(rpc_url=args.rpc, interval=args.interval)
    
    if args.daemon:
        return watcher.run_daemon()
    else:
        if not watcher.connect():
            return 1
        
        result = watcher.check_once()
        print(json.dumps(result, indent=2))
        return 0


if __name__ == "__main__":
    sys.exit(main())